NinfasVips/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Junior Rodrigues'

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from yawdadmin import admin_site
from ninfas.models import *

admin.autodiscover()
admin_site._registry.update(admin.site._registry)
admin_site.register_top_menu_item('auth', icon_class="icon-th")
admin_site.register_top_menu_item('ninfas', icon_class="icon-th")
admin_site.register_top_menu_item('publicidades', icon_class="icon-th")
admin_site.register_top_menu_item('mensalidades', icon_class="icon-th")

import settings

urlpatterns = patterns('',
    url(r'^admin/', include(admin_site.urls)),
    (r'^ckeditor/', include('lib.ckeditor.urls')),
    (r'^assunto/(?P<slugcategoria>[\w_-]+)/', include('lib.tagging.urls')),
    (r'^tagging_autocomplete/', include('lib.tagging_autocomplete.urls')),
    (r'^ninfas/(?P<sluguf>[\w_-]+)/$', 'ninfas.views.ninfasestado'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += patterns('ninfas.views',
     (r'^ninfas/(?P<slugcor>[\w_-]+)/$', 'ninfascor'),
     url(r'^$', 'capa', name='homepage'),

     (r'^ninfas/(?P<sluguf>[\w_-]+)/(?P<slugcidade>[\w_-]+)/(?P<slugninfa>[\w_-]+)/$', 'ninfainterna'),
     (r'^ninfas/(?P<sluguf>[\w_-]+)/(?P<slugcidade>[\w_-]+)/$', 'ninfascidade'),


     (r'^ninfas/$', 'ninfas'),
     (r'^vips/$', 'vips'),

)

if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Arquivos enviados pelo usuário
    urlpatterns += staticfiles_urlpatterns()

lib/tagging/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Junior Lima'
from django.conf.urls.defaults import *

urlpatterns = patterns('lib.tagging.views',
    url(r'^(?P<tag_name>.*?)/$', 'tag', name='tag'),
    url(r'^(?P<tag_name>.*?)$', 'tag', name='tag'),
)

ninfas/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

from core.destino_imagem import acompanhante, acompanhante_galeria
from core.thumbs import ImageWithThumbsField

def destino_imagem_galeria(instance, filename):
    return '/'.join(['fotos', str(instance.galeria.slug), filename])

class Cor(models.Model):
    nome = models.CharField(max_length=150)
    descricao = models.TextField(blank=True, null=True)
    slugcor = models.SlugField(blank=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Cor'
        verbose_name_plural = 'Cor'

    def get_absolute_url(self):
        return reverse('ninfas.views.ninfascor', kwargs={'slugcor': self.slugcor})


class Estado(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    uf = models.CharField(max_length=100, blank=True, null=True)
    sluguf = models.SlugField(blank=True)
    slugestado = models.SlugField(blank=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'

class Cidades(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    estado = models.ForeignKey(Estado)
    slugcidade = models.SlugField(blank=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Cidade'
        verbose_name_plural = 'Cidades'

    def get_absolute_url(self):
        return reverse('ninfas.views.ninfascidade', kwargs={'sluguf':self.estado.sluguf,'slugcidade': self.slugcidade})


class Hobby(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Hoob'
        verbose_name_plural = 'Hoobs'

class Musicas(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Música'
        verbose_name_plural = 'Músicas'

class Idiomas(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Idioma'
        verbose_name_plural = 'Idiomas'

class Meses(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Mês'
        verbose_name_plural = 'Meses'

class Acompanhantes(models.Model):
    status = models.BooleanField(default=True)
    destaque = models.BooleanField(blank=True)
    vip = models.BooleanField(blank=True)
    nome = models.CharField(max_length=190, unique=True)
    descricao = models.CharField(max_length=255, blank=True, null=True)
    cor = models.ForeignKey(Cor, blank=True, null=True,default=1)
    cidade = models.ForeignKey(Cidades)
    altura = models.CharField(max_length=100, help_text='1,60cm')
    idade = models.IntegerField(blank=True, null=True)
    hobby = models.ManyToManyField(Hobby,blank=True, null=True)
    musica = models.ManyToManyField(Musicas,blank=True, null=True)
    quadris = models.CharField(max_length=50, help_text='60cm',blank=True, null=True)
    cartao = models.BooleanField('Aceita Cartão?',blank=True)
    visa = models.BooleanField(blank=True)
    master = models.BooleanField(blank=True)
    credishop = models.BooleanField(blank=True)
    viaja = models.BooleanField(blank=True)
    idiomas = models.ManyToManyField(Idiomas,blank=True, null=True)
    contato = models.CharField(max_length=50,help_text='99.9999-9999')
    celular = models.CharField(max_length=50,help_text='99.9999-9999',blank=True, null=True)
    email = models.EmailField(help_text='seuemail@email.com',blank=True, null=True)
    site =  models.URLField(blank=True, null=True)

    imagem_capa = ImageWithThumbsField('Imagem Capa', upload_to=acompanhante, sizes=((800,600),(300,225),(212,318)))
    imagem_destaque = ImageWithThumbsField('Imagem Destaque', upload_to=acompanhante, sizes=((800,600),(212,318)),blank=True,null=True)

    valor = models.FloatField('Valor Mensalidade: R$',help_text='130.00', blank=True, null=True)
    vencimento = models.IntegerField(blank=True, null=True)

    criado_em = models.DateTimeField(auto_now_add=True)
    cliques = models.IntegerField('Cliques', default=0, editable=False)
    slug = models.SlugField(blank=True)

    def __unicode__(self):
        return  self.nome
    class Meta:
        verbose_name = 'Acompanhante'
        verbose_name_plural = 'Acompanhantes'

    def get_absolute_url(self):
        return reverse('ninfas.views.ninfainterna', kwargs={'slugcidade':self.cidade.slugcidade,'sluguf':self.cidade.estado.sluguf,'slugninfa': self.slug})


class Imagem(models.Model):
    foto = ImageWithThumbsField('Imagem Destaque', upload_to=acompanhante_galeria, sizes=((918,573),(170,127)))
    galeriaImagem = models.ForeignKey(Acompanhantes, related_name='galeriaImagem')
    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'


# SIGNALS
from django.db.models import signals, ImageField
from django.template.defaultfilters import slugify

def acompanhante_pre_save(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.nome)

signals.pre_save.connect(acompanhante_pre_save, sender=Acompanhantes)

def estado_pre_save(signal, instance, sender, **kwargs):
    instance.sluguf = slugify(instance.uf)
    instance.slugestado = slugify(instance.nome)

signals.pre_save.connect(estado_pre_save, sender=Estado)

def cidade_pre_save(signal, instance, sender, **kwargs):
    instance.slugcidade = slugify(instance.nome)

signals.pre_save.connect(cidade_pre_save, sender=Cidades)

def cor_pre_save(signal, instance, sender, **kwargs):
    instance.slugcor = slugify(instance.nome)

signals.pre_save.connect(cor_pre_save, sender=Cor)

templates/ninfas/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <title>Ninfas Vip's</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="jQuery Responsive Carousel - Owl Carusel">
    <meta name="author" content="Bartosz Wojciechowski">
    <!--
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,700' rel='stylesheet' type='text/css'>-->
    <link href="{{ STATIC_URL }}site/assets/css/bootstrapTheme.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}site/assets/css/custom.css" rel="stylesheet">

    <!-- Owl Carousel Assets -->
    <link href="{{ STATIC_URL }}site/owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}site/owl-carousel/owl.theme.css" rel="stylesheet">

    <!-- Prettify -->
    <link href="{{ STATIC_URL }}site/assets/js/google-code-prettify/prettify.css" rel="stylesheet">


    <!-- Le fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ STATIC_URL }}site/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}site/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}site/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}site/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="{{ STATIC_URL }}site/assets/ico/favicon.png">
</head>
<body class="interna-win">
<div class="row">
    <div class="span10">
        <div class="offset3">
            <div class="logo-home">
                <div class="box-home">
                    <div class="limite">
                        <span class="title-box">selecione sua cidade para Entrar</span>
                        <div id="mainselection" style="margin-top: 19px;">

                          <select name="forma" onchange="location = this.options[this.selectedIndex].value;">
                            <option value="">SELECIONE SUA CIDADE</option>
                            {% for cidade in cidades %}
                                 <option value="{{ cidade.get_absolute_url }}">{{ cidade.nome }}/{{ cidade.estado.uf }}</option>
                            {% endfor %}
                          </select>
                        </div>
                        <a href="/ninfas">
                            <div class="button-home">ENTRAR</div>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/ninfas/ninfas-geral.html
{% include "header/header.html" %}

    <div id="demo" class="destaque">
        <div class="container">
          <div class="row">
            <div class="span8">
              <div id="owl-demo-full" class="owl-carousel">
                {% for destaque in destaque %}
                    <a href="{{ destaque.get_absolute_url }}">
                        <div class="item">
                            <span class="cartoes">
                                {% if destaque.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if destaque.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <span class="descricao-ninfa">
                                    <h1>{{ destaque.nome }}</h1>
                                    <h4 class="subtitulo">{{ destaque.descricao }}</h4>
                            </span>
                            <img src="{{ destaque.imagem_destaque.url_800x600 }}" alt="{{ destaque.nome }}">

                        </div>
                    </a>
                {% endfor %}

              </div>

            </div>

          {% include "sidebar/sidebar-home.html" %}
          </div>
        </div>
    </div>

<div class="row section-ninfas">

    <div id="title" class="title">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h1>Vips da Semana</h1>
          </div>
        </div>
      </div>
    </div>

      <div id="demo">
        <div class="container">
          <div class="row">
            <div class="span12">

              <div id="owl-demo" class="owl-carousel new-height">
                  {% for ninfa in semana|slice:"0:5" %}
                      <a href="{{ ninfa.get_absolute_url }}">
                        <div class="item">
                            <span class="cartoes">
                                {% if ninfa.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if ninfa.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <img class="lazyOwl" data-src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                            <span class="descricao-ninfa">
                                <h3>{{ ninfa.nome }}</h3>
                            </span>
                        </div>
                      </a>
                  {% endfor %}
              </div>

            </div>

          </div>
        </div>

    </div>
</div>


<div class="row section-ninfas-morenas">
{% for ninfacidade in cidades %}
    <div id="title" class="title">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h1>Ninfas de {{ ninfacidade.nome }}
                <a href="/ninfas/{{ ninfacidade.estado.sluguf }}/{{ ninfacidade.slugcidade }}">
                    <ul class="nav pull-right menu-categoria">

                            <li class="">
                                  MAIS DE {{ ninfacidade.nome }}
                            </li>

                  </ul>
                    </a>
            </h1>

          </div>
        </div>
      </div>
    </div>

      <div id="demo">
        <div class="container">
          <div class="row">


            <div class="span12">

                      <div id="owl-demo-row-{{ ninfacidade.slugcidade }}" class="categoria-geral">
                        {% for ninfa in ninfacidade.acompanhantes_set.all|slice:"0:4" %}
                              <a href="{{ ninfa.get_absolute_url }}">
                                <div class="item">
                                    <div class="fade-home"></div>
                                    <span class="cartoes">
                                        {% if ninfa.master == 1 %}
                                        <span class="master">
                                            <img src="{{ STATIC_URL }}site/img/master.png">
                                        </span>
                                        {% endif %}
                                        {% if ninfa.visa == 1 %}
                                            <span class="master">
                                                <img src="{{ STATIC_URL }}site/img/visa.png">
                                            </span>
                                        {% endif %}
                                    </span>
                                    <img class="lazyOwl" src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                                    <span class="descricao-ninfa">
                                        <h3>{{ ninfa.nome }}</h3>
                                    </span>
                                </div>
                              </a>
                            {% endfor %}
                      </div>



            </div>



          </div>
        </div>

    </div>
    <style type="text/css">
                        #owl-demo-row-{{ ninfacidade.slugcidade }}
                        {
                            float: left;
                            position: relative;
                            width: 102%;
                        }
                        #owl-demo-row-{{ ninfacidade.slugcidade }} .item{
                            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.3);
                            float: left;
                            height: 330px;
                            margin-left: 17px;
                            overflow: hidden;
                            position: relative;
                            width: 23%;
                        }
                        .categoria-geral
                        {
                            float: left;
                            position: relative;

                        }
                        #owl-demo-row-{{ ninfacidade.slugcidade }} .item img{
                            display: block;
                            width: 100% !important;
                            height: auto !important;
                            border-radius: 3px;

                            -webkit-transition: height 500ms ease-in-out;
                            -moz-transition: height 500ms ease-in-out;
                            -ms-transition: height 500ms ease-in-out;
                            -o-transition: height 500ms ease-in-out;
                            transition: height 500ms ease-in-out;
                        }
                     </style>

    <script>
    $(document).ready(function() {
        $("#owl-demo-row-{{ ninfacidade.slugcidade }}").owlCarousel({
        items : 4,
        lazyLoad : true,
        navigation : true,
          autoPlay: 9000
      });

    });
    </script>
{% endfor %}

</div>
{% include "footer/footer.html" %}

templates/ninfas/ninfas.html
{% include "header/header.html" %}

    <div id="demo" class="destaque">
        <div class="container">
          <div class="row">
            <div class="span8">
              <div id="owl-demo-full" class="owl-carousel">
                {% for destaque in destaque %}
                    <a href="{{ destaque.get_absolute_url }}">
                        <div class="item">
                            <div class="fade-home"></div>
                            <span class="cartoes">
                                {% if destaque.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if destaque.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <span class="descricao-ninfa">
                                    <h1>{{ destaque.nome }}</h1>
                                    <h4 class="subtitulo">{{ destaque.descricao }}</h4>
                            </span>
                            <img src="{{ destaque.imagem_destaque.url_800x600 }}" alt="{{ destaque.nome }}">

                        </div>
                    </a>
                {% endfor %}

              </div>

            </div>

          {% include "sidebar/sidebar-home.html" %}
          </div>
        </div>
    </div>

<div class="row section-ninfas">

    <div id="title" class="title">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h1>Ninfas da Semana</h1>
          </div>
        </div>
      </div>
    </div>

      <div id="demo">
        <div class="container">
          <div class="row">
            <div class="span12">

              <div id="owl-demo" class="owl-carousel new-height">
                  {% for ninfa in semana|slice:"0:5" %}
                      <a href="{{ ninfa.get_absolute_url }}">
                        <div class="item">
                            <div class="fade-home"></div>
                            <span class="cartoes">
                                {% if ninfa.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if ninfa.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <img class="lazyOwl" data-src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                            <span class="descricao-ninfa">
                                <h3>{{ ninfa.nome }}</h3>
                            </span>
                        </div>
                      </a>
                  {% endfor %}
              </div>

            </div>

          </div>
        </div>

    </div>
</div>

<div class="row section-ninfas-morenas">

    <div id="title" class="title">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h1>Ninfas</h1>
          </div>
        </div>
      </div>
    </div>

      <div id="demo">
        <div class="container">
          <div class="row">
            <div class="span12">

              <div id="owl-demo-row" class="owl-carousel new-height">
                  {% for ninfa in semana|slice:"5:9" %}
                      <a href="{{ ninfa.get_absolute_url }}">
                        <div class="item">
                            <span class="cartoes">
                                {% if ninfa.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if ninfa.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <img class="lazyOwl" data-src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                            <span class="descricao-ninfa">
                                <h3>{{ ninfa.nome }}</h3>
                            </span>
                        </div>
                      </a>
                  {% endfor %}
              </div>

            </div>

          <div class="span12">

              <div id="owl-demo-row-three" class="owl-carousel new-height" style="margin-top: 15px">
                  {% for ninfa in semana|slice:"9:13" %}
                      <a href="{{ ninfa.get_absolute_url }}">
                        <div class="item">
                            <span class="cartoes">
                                {% if ninfa.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if ninfa.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <img class="lazyOwl" data-src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                            <span class="descricao-ninfa">
                                <h3>{{ ninfa.nome }}</h3>
                            </span>
                        </div>
                      </a>
                  {% endfor %}
              </div>

            </div>

          <div class="span12">

              <div id="owl-demo-row-two" class="owl-carousel new-height" style="margin-top: 15px">
                  {% for ninfa in semana|slice:"13:17" %}
                      <a href="{{ ninfa.get_absolute_url }}">
                        <div class="item">
                            <span class="cartoes">
                                {% if ninfa.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if ninfa.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <img class="lazyOwl" data-src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                            <span class="descricao-ninfa">
                                <h3>{{ ninfa.nome }}</h3>
                            </span>
                        </div>
                      </a>
                  {% endfor %}
              </div>

            </div>

          </div>
        </div>

    </div>
</div>

{% for cor in catcor %}
<div class="row section-ninfas-morenas">

    <div id="title" class="title">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h1>{{ cor.nome }}s</h1>
          </div>
        </div>
      </div>
    </div>

      <div id="demo">
        <div class="container">
          <div class="row">
            <div class="span12">

              <div id="owl-demo-row-morenas" class="owl-carousel new-height">
                  {% for ninfa in cor.acompanhantes_set.all|slice:"0:5" %}
                      <a href="{{ ninfa.get_absolute_url }}">
                        <div class="item">
                        <div class="fade-home"></div>
                            <span class="cartoes">
                                {% if ninfa.master == 1 %}
                                <span class="master">
                                    <img src="{{ STATIC_URL }}site/img/master.png">
                                </span>
                                {% endif %}
                                {% if ninfa.visa == 1 %}
                                    <span class="master">
                                        <img src="{{ STATIC_URL }}site/img/visa.png">
                                    </span>
                                {% endif %}
                            </span>
                            <img class="lazyOwl" data-src="{{ ninfa.imagem_capa.url_212x318 }}" alt="Lazy Owl Image">
                            <span class="descricao-ninfa">
                                <h3>{{ ninfa.nome }}</h3>
                            </span>
                        </div>
                      </a>
                  {% endfor %}
              </div>

            </div>

          </div>
        </div>

    </div>
</div>
{% endfor %}
{% include "footer/footer.html" %}